# MySQL
development:
  adapter:  mysql
  username: root
  password: root
  url: "jdbc:mysql://localhost:3306/holarse_development"
  encoding: utf8

test:
  adapter:  mysql
  username: root
  password: root
  url: "jdbc:mysql://localhost:3306/holarse_test"
  encoding: utf8
