# MySQL
development:
  adapter:  mysql
  username: holarse2014
  password: holarse2014
  url: "jdbc:mysql://localhost:3306/holarse2014_development"
  encoding: utf8

test:
  adapter:  mysql
  username: travis
  url: "jdbc:mysql://localhost:3306/holarse2014_test"
  encoding: utf8
