development:
  adapter: jdbcpostgresql
  encoding: unicode
  host: localhost
  database: holarse_development
  username: postgres
  pool: 8

test:   
  adapter: jdbcpostgresql
  encoding: unicode
  host: localhost
  database: holarse_testing
  username: postgres
  pool: 8


